sudo: required
language: node_js
addons:
  chrome: stable
install: npm install
before_install:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script:
  - if [ $ENV == 'browser' ]; then npm run test-browser; fi
  - npm run build
